#多数据源
com:
  sl:
    datasource:
      multi:
        -
          ds-name: sl-core
          driver-class-name: com.mysql.cj.jdbc.Driver
          primary: true
          url: jdbc:mysql://139.196.126.165:3306/sl_core?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: sldb
          password: Sl123qwe!
        -
          ds-name: sl-test
          primary: false
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://139.196.126.165:3306/sl_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: sldb
          password: Sl123qwe!


#日志
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      sl:
        dao: debug
    root: info
#端口号
server:
  port: 1106
#shiro
shiro:
  redis:
    expire: 1800
    timeout: 0
#国际化
spring:
  messages:
    basename: i18n/message
  #redis
  redis:
    database: 6
    host: 127.0.0.1
    password: ''
    port: 6379

user:
  name: ttttt
